Add CA check to functions.

diff --git a/create-server b/create-server
--- a/create-server
+++ b/create-server
@@ -13,6 +13,9 @@
 # get system variables if needed
 . ./vars
 
+# make sure there is a Certificate Authority for this system.
+ca_check
+
 usage (){
     printf "
 Usage: $0 certificate_name template [nopass]
@@ -31,13 +34,18 @@ List of template files:
     fi
 }
 
-# STEP 1 - check if the right number of parameters were supplied.
+# STEP 1 - clean up aborted certificate creation attempts
+rm -f $SETUP_DIR/easyrsa3/pki/private/*.key.*
+rm -f $SETUP_DIR/easyrsa3/pki/reqs/*.req.*
+rm -f $SETUP_DIR/easyrsa3/pki/issued/*.crt.*
+
+# STEP 2 - check if the right number of parameters were supplied.
 if [ $# -lt 2 ] ; then
     usage
     exit 1
 fi
 
-# STEP 2 - check to see if template file exists
+# STEP 3 - check to see if template file exists
 TEMPLATE="${2//.template}"
 if [ ! -f ./templates/$TEMPLATE.template ];
     then
@@ -45,24 +53,25 @@ if [ ! -f ./templates/$TEMPLATE.template ];
         exit 1
 fi
 
-# STEP 3 - check to see if tls-auth key file exists
+# STEP 4 - check to see if diffie-hellman key file exists
+if [ ! -f ./easyrsa3/pki/dh.pem ] ; then
+    printf "Error DH: ./easyrsa3/pki/dh.pem does not exist\n"
+    exit 1
+fi
+
+# STEP 5 - check to see if tls-auth key file exists
 if [ ! -f ./easyrsa3/pki/ta.key ] ; then
     printf "Error TA: ./easyrsa3/pki/ta.key does not exist\n"
     exit 1
 fi
 
-# STEP 4 - check to see if certificate authority key exists
+# STEP 6 - check to see if certificate authority key exists
 if [ ! -f ./easyrsa3/pki/private/ca.key ] ; then
     printf "Error CA: ./easyrsa3/pki/private/ca.key does not exist\n"
     exit 1
 fi
 
-# STEP 5 - clean up aborted certificate creation attempts
-rm -f $SETUP_DIR/easyrsa3/pki/private/*.key.*
-rm -f $SETUP_DIR/easyrsa3/pki/reqs/*.req.*
-rm -f $SETUP_DIR/easyrsa3/pki/issued/*.crt.*
-
-# STEP 6 - see if certificate already exists. If so then skip creating another one.
+# STEP 7 - see if certificate already exists. If so then skip creating another one.
 CERT="${1//.crt}"
 if [ ! -f ./easyrsa3/pki/issued/$CERT.crt ];
     # if certificate does not exist remove any intermediate key and req files.
@@ -85,33 +94,33 @@ if [ ! -f ./easyrsa3/pki/issued/$CERT.crt ];
         printf "Certificate easyrsa/pki/issued/$CERT.crt already exists.\n"
 fi
 
-# STEP 7 - check to see if certificate is created.
+# STEP 8 - check to see if certificate is created.
 if [ ! -f ./easyrsa3/pki/issued/$CERT.crt ] ; then
     printf "Error CRT: ./easyrsa3/pki/issued/$CERT.crt was not created.\n"
     exit 1
 fi
 
-# STEP 8 - check to see if key file exists.
+# STEP 9 - check to see if key file exists.
 #          note: key file should exist if certificate exist.
 if [ ! -f ./easyrsa3/pki/private/$CERT.key ] ; then
     printf "Error KEY: ./easyrsa3/pki/private/$CERT.key does not exist. Try ./delete-config first.\n"
     exit 1
 fi
 
-# STEP 9 - make sure the "server" sub directory exists. If not create it.
+# STEP 10 - make sure the "server" sub directory exists. If not create it.
 if [ ! -d servers ] ; then
     printf "Creating directory ./servers for server config files.\n"
     mkdir servers
 fi
 
-# STEP 10 - make sure the "ccd" directory exists. If not create it.
+# STEP 11 - make sure the "ccd" directory exists. If not create it.
 if [ ! -d ccd ] ; then
     printf "Creating directory ./ccd for server-side client config files.\n"
     mkdir ccd
 fi
 
 
-# STEP 11 - We seem to have everything we need to create configuration file.
+# STEP 12 - We seem to have everything we need to create configuration file.
 #
 # copy over template
 cp ./templates/$TEMPLATE.template ./servers/$CERT.conf
diff --git a/vars b/vars
--- a/vars
+++ b/vars
@@ -27,18 +27,38 @@ ZIPFILE="$UPDATE_DIR/vpn-setup.zip"
 
 
 function verify {
-    if  [ $# -gt 0 ] ; then
-        printf "$1"
-    else
-        printf "Verify 'yes' or 'no' > "
-    fi
+    while true ; do
+        if  [ $# -gt 0 ] ; then
+            printf "$1"
+        else
+            printf "Verify 'YES' or 'NO' > "
+        fi
 
-    read USERINPUT
+        read USERINPUT
 
-    if [ $USERINPUT == "yes" ] || [ $USERINPUT == "YES" ] || [ $USERINPUT == "Yes" ] ; then
-        return 0
-    else
-        return 1
-    fi
-
+        if [[ -z "$USERINPUT" ]]; then
+            continue
+        fi
+            
+        if [ ${USERINPUT^^} == "YES" ] ; then
+            printf 'YES\n'
+            exit 0
+	    fi
+    	if [ ${USERINPUT^^} == "NO" ] ; then
+    	    printf 'NO\n'
+            exit 1
+    	fi
+    done
 }
+
+function ca_check {
+    # see if system has been initialized and the CA created.
+    if [ ! -f "$SETUP_DIR/easyrsa3/pki/ca.crt" ] ; then
+        printf "ERROR: The system has not been initialized. Run ./build-new to initialize.\n" 
+        exit 10
+    fi              
+    if [ ! -f "$SETUP_DIR/easyrsa3/pki/private/ca.key" ] ; then
+        printf "ERROR: The keys have been removed.  Run ./restore-keys and try again.\n" 
+        exit 11
+    fi              
+}    
